((go-mode . ((eval . (let* ((project-root (->> ".dir-locals.el"
                                               (locate-dominating-file default-directory)
                                               (file-truename)))
                            (go-path (concat project-root ".go"))
                            (go-bin (f-join go-path "bin"))
                            (path (->> (or (getenv "PATH") "")
                                       (s-split ":")
                                       (append (list go-bin) exec-path)
                                       (seq-uniq))))
                       (setenv "GOPATH" go-path)
                       (setenv "PATH" (s-join ":" path))
                       (setq exec-path path))))))
